### ISSUE TITLE
The live-reload URL is pinned even when manually changing the URL

### ISSUE THREAD

**Issue by wmertens** [mark-hahn/web-browser#36]
When live-reloading, the URL that was enabled at the start will be used even when manually changing the URL.

Related, if you're in a single-page app that changes the URL, this will reset the URL to the beginning one.

**Comment by mark-hahn** [comment]
This seems like a regression bug.  I'll get to these today.

**Comment by mark-hahn** [comment]
>  the URL that was enabled at the start will be used even when manually changing the URL.

I wrote the code so that the start url is saved and always used when auto-reloading.  That is supposed to be a feature. The idea is that when testing and you change the source you will be starting the debug cycle over again and you want to start at the fixed url-under-test.  In order to change the url for a tab you have to hit the auto-reload button twice while that tab is at the new URL.

This may be a bad idea.  I'm welcome to other ideas.  In any case this should be in the docs.

**Comment by wmertens** [comment]
How about, when you enable auto-reload, there's an extra button for locking
the URL?

**Comment by mark-hahn** [comment]
> How about, when you enable auto-reload, there's an extra button for locking
the URL?

I'll do something to give you the option.  Maybe ctrl-click the auto-reload button.

**Comment by wmertens** [comment]
Hmm, that's not a very discoverable UI... but better than nothing :)

**Comment by mark-hahn** [comment]
How about a package setting?

**Comment by wmertens** [comment]
That works!

**Comment by mark-hahn** [comment]
This web-browser package is no longer supported.  Use the atom package browser-plus instead.
