### ISSUE TITLE
Merge with atom-browser-view?

### ISSUE THREAD

**Issue by sedabull** [mark-hahn/web-browser#7]
Just a quick question, because I'm really interested in using this package. I saw the discussion over at gstack/atom-browser-view#1 and was wondering what ever became of it. I'd rather not download a temporary/unofficial package.

**Comment by mark-hahn** [comment]
He was going to do a PR but I haven't seen it yet.  When even talked about collaborating on that and other packages.

I'm sorry for the delay.  I probably should have put in a kludge to work around the chrome bug in the beginning but I've been so busy I didn't want to waste time on something that will be replaced.  The good news is that the chrome bug has been fixed but atom/atom-shell can't include it until a problem is fixed in the release.  See https://github.com/atom/atom-shell/pull/1002

I have also been holding off on many planned improvements.  I'll be excited to continue work on it.

**Comment by sedabull** [comment]
I'll be looking forward to see where this project goes, and I completely understand getting caught up in other things, thanks for the feedback :+1: .

**Comment by mark-hahn** [comment]
Apparently the merge is not happening.  Hopefully I will get the real webview working soon.

**Comment by sedabull** [comment]
sounds good, I'd be interested in testing the beta once you have something working. I'm still pretty new at all of this, but I learn best by doing, so just ping me if you're interested. I'd consider it a valuable learning experience.

**Comment by mark-hahn** [comment]
I'll keep you in mind for beta.
